Add getAllTasks query inside rtk query api
faysal-alam-sazim/fancy-todo-app pull request #24
Opened 2024-08-06 12:02 UTC by faysal-alam-sazim

### Description of Change
- Added a query inside rtk api
- Query is for get all tasks
### Associated Ticket Link:
- https://trello.com/c/esZLZRWr
### Related Pull Request: N/A
### Screenshots / Screen Recordings: N/A

2024-08-06 18:22 UTC, ishmam-iqbal-sazim commented on shared/redux/store.ts
> +import { api } from "./rtk-apis/tasksAPI";
```suggestion
import { configureStore } from "@reduxjs/toolkit";

import { api } from "./rtk-apis/tasksAPI";
```

Should be a line gap between library and relative imports

2024-08-06 18:31 UTC, ishmam-iqbal-sazim commented on shared/components/TaskModal/TaskModal.tsx
> +      >
Why are we only validating due date? Please add a ticket to address form validation.

2024-08-06 18:32 UTC, ishmam-iqbal-sazim approved these changes
Approved pending comments.

2024-08-06 19:31 UTC, ragib-hossain-sazim approved these changes
This PR is not rebased properly, there is a lot of unrelated changes. Please rebase before merging.

2024-08-06 19:32 UTC, ragib-hossain-sazim requested changes
Should this be pointed to main?

2024-08-07 05:43 UTC, faysal-alam-sazim commented
> Should this be pointed to main?

No this PR should point at the latest branch from this created. I forgot change the pointing branch. But now the latest branch is merged with main. It now should point at main.

2024-08-08 17:23 UTC, ragib-hossain-sazim approved these changes

2024-08-09 08:54 UTC, merged